### PR TITLE
fix #1357 hero children width shouldnt depend on siblings

### LINKED ISSUE #1357: image in mj-hero becomes smaller while adding a mj-section after the mj-hero
When adding a `mj-section` below an `mj-hero`, where the `mj-hero` has no width defined, an image inside an `mj-hero` becomes smaller and smaller when more `mj-section`s are added

Refs https://github.com/mjmlio/mjml/pull/1320#issuecomment-423950858

**Reproduction Steps:**

Pick the following MJML

```
<mjml>
  <mj-body background-color="#FAFAFA" width="594px">
    <mj-hero mode="fluid-height" background-color="#335366" background-width="100%" padding="27px 18px">
      <mj-image href="https://magnet.me/?utm_content=magnet-logo" src="https://cdn.magnet.me/images/press/logos/logo_full_white.png" align="center" padding="0px" width="172px"></mj-image>
    </mj-hero>
  </mj-body>
</mjml>
```

And run in in the try it live version (or a version locally, same result) on MJML 4.1.2

Adding three empty `mj-section`s below renders the following MJML, and shrinks the image in the hero

```
<mjml>
  <mj-body background-color="#FAFAFA" width="594px">
    <mj-hero mode="fluid-height" background-color="#335366" background-width="100%" padding="27px 18px">
      <mj-image href="https://magnet.me/?utm_content=magnet-logo" src="https://cdn.magnet.me/images/press/logos/logo_full_white.png" align="center" padding="0px" width="172px"></mj-image>
    </mj-hero>
    <mj-section></mj-section>
    <mj-section></mj-section>
    <mj-section></mj-section>
  </mj-body>
</mjml>
```

**Expected behavior:**

Do not shrink an image of another element

**Observed behavior:**

The image is shrunk for each `mj-section` added after the first one

**Screenshots and GIFs**

https://mjml.io/try-it-live/Bko3gIUFm

**MJML version:**

4.1.2

**Email clients the bug is seen on:**

Any client

### PR DESCRIPTION
**Pull request by kmcb777**
the `siblings` prop is no longer used anywhere since column now use `nonRawSiblings`, should we remove it ?

### CODE REVIEW

File: packages/mjml-hero/src/index.js [hunk 1]
```diff
@@ -48,13 +48,12 @@ export default class MjHero extends BodyComponent {
...
     // Refactor -- removePaddingFor(width, ['padding', 'inner-padding'])
     const { containerWidth } = this.context
-    const { sibling } = this.props
     const paddingSize =
       this.getShorthandAttrValue('padding', 'left') +
       this.getShorthandAttrValue('padding', 'right')
 
     let currentContainerWidth =
-      this.getAttribute('width') || `${parseFloat(containerWidth) / sibling}px`
+      this.getAttribute('width') || `${parseFloat(containerWidth)}px`
```
Comment (iRyusa) [inline packages/mjml-hero/src/index.js]:
```suggestion
  `${parseFloat(containerWidth)}px`
```
`width` isn't a supported attribute for `mj-hero` I think

**Comment by kmcb777** [comment]
removed other references to width in Hero component and documentation
