### PR TITLE
fix image size when border

### LINKED ISSUE #1094: mj-image in mj-group does not respect width or CSS min-width on Android Gmail
Hello,

I am experiencing a rendering issue with Android clients when trying to render an `mj-image` inside of an `mj-group`; the Android clients do not seem to care about the `width` MJML attribute or the `min-width` CSS attribute. This leads to the image having a distorted aspect ratio when the screen size begins to shrink (see screenshots). 

### Reproduction Steps:

1. Use `mjml2html` to compile the following MJML to HTML:
```mjml
<mjml>
    <mj-head>
        <mj-attributes>
            <mj-all font-family="Helvetica, Arial, sans-serif"/>
            <mj-text font-size="16px"
                     color="#414247"
                     line-height="22px"/>
        </mj-attributes>
        <mj-style>
            p {
                margin: 0;
            }
        </mj-style>
    </mj-head>
    <mj-body>
        <mj-section padding="0 0 10px 0"
                    border-radius="4px">
            <mj-group width="70%">
                <mj-column vertical-align="middle"
                           width="25%">
                    <mj-image
                            src="https://storage.googleapis.com/accounts-content/590789031630f717a458c889-portrait_original-e6a96d18-df1c-4cc2-842b-af3a1e196655.jpg"
                            border-radius="50%"
                            height="48px"
                            width="48px"
                            align="right"
                            padding="10px 15px 10px 25px"/>
                </mj-column>
                <mj-column vertical-align="middle"
                           width="75%">
                    <mj-text color="#023082"
                             padding="0 0 2px 0"
                             align="left">
                        Drake
                    </mj-text>
                    <mj-text font-size="13px"
                             color="#717171"
                             padding="2px 0 0 0"
                             line-height="18px"
                             align="left">
                        Marketing &amp; Communications Manager
                    </mj-text>
                </mj-column>
            </mj-group>
            <mj-column width="30%"
                       vertical-align="middle">
                <mj-button background-color="#2637DE">CTA!</mj-button>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```
2. Copy and paste the outputted HTML into [Litmus](https://litmus.com)
3. See expected behaviour in iPhone screen captures and observed behaviour in Android screen captures

### Expected behavior:

- When screen shrinks, padding should shrink and image width should be respected

### Observed behavior:

- When screen shrinks on Android, image width gets reduced, resulting in a distorted aspect ratio

### Screenshots and GIFs

**iPhone screenshot with expected image width**
iphone6s-vertical-allowed-1366

**Android 6.0 (Android 6.0) with distorted aspect ratio***
android6-vertical-allowed-1366

**Gmail App (Android 6.0) with distorted aspect ratio***
androidgmailapp-vertical-allowed-1366

**Gmail App IMAP (Android 4.4) with distorted aspect ratio**
androidgmailimap-vertical-allowed-1366

### MJML version:

`v4.0.2`

### Email clients the bug is seen on:

- Android 6.0 (Android 6.0)
- Gmail App (Android 6.0)
- Gmail App IMAP (Android 4.4)

### PR DESCRIPTION
**Pull request by kmcb777**
border was not included in width calculation, causing image with border to overflow from column, and not be centered properly

Also fixes #1094 
Also fixes a bug on outlook 2003 that makes mj-images to take much more space than the actual image, which messes up mj-columns that contains them

### CODE REVIEW

File: packages/mjml-core/src/createComponent.js [hunk 1]
```diff
@@ -87,6 +87,13 @@ export class BodyComponent extends Component {
     return shorthandParser(mjAttribute, direction)
   }
 
+  getShorthandBorderValue(direction) {
+    const borderDirection = this.getAttribute(`border-${direction}`)
+    const border = this.getAttribute('border')
```
Comment (iRyusa) [inline packages/mjml-core/src/createComponent.js]: how does it works when you have something like `border: 1px solid red` ? Will it parse it correctly?

**Comment by iRyusa** [comment]
Shouldn't we apply this logic to section/column too ?
Remove border left/right from the width ?

**Comment by kmcb777** [comment]
@iRyusa done on section and column

File: packages/mjml-image/src/index.js [hunk 2]
```diff
@@ -74,26 +78,20 @@ export default class MjImage extends BodyComponent {
...
     const { containerWidth } = this.context
-
     const width = this.getAttribute('width')
-      ? min([
-          parseInt(this.getAttribute('width'), 10),
-          parseInt(containerWidth, 10),
-        ])
-      : parseInt(containerWidth, 10)
+                ? parseInt(this.getAttribute('width'), 10)
+                : Infinity
```
Comment (iRyusa) [inline packages/mjml-image/src/index.js]: Mhh, i'm not confident about that infinity here. Could it lead to some issue ?

File: packages/mjml-column/src/index.js [hunk 3]
```diff
@@ -34,6 +34,12 @@ export default class MjColumn extends BodyComponent {
     const paddingSize =
       this.getShorthandAttrValue('padding', 'left') +
       this.getShorthandAttrValue('padding', 'right')
+      
+    const border =
+      this.getShorthandBorderValue('right') +
+      this.getShorthandBorderValue('left')
+
+    const allPaddings = paddingSize + border
```
Comment (iRyusa) [inline packages/mjml-column/src/index.js]: I think the naming is a bit ugly here, since it does basically the job of box-sizing:border-box maybe we could create some kind of helper that would get an object of attributes and output an object `{ box:  450, border: 20, padding: 20, totalWidth: 490 }`

So it can be tested properly ?

Comment (kmcb777) [reply packages/mjml-column/src/index.js]: okay i'll do something like this 👍
