### PR TITLE
fix(mjml-table): cellspacing  is respected #2995

### LINKED ISSUE #2995: mj-table does not respect cellspacing attribute
**Describe the bug**
When applying `cellspacing`, the result ignores the set value due to `border-collapse` being set to `collapse`.

**To Reproduce**
https://mjml.io/try-it-live/qWRH2wFJDD

**Expected behavior**
There should be visible cellspacing around the table cells

**MJML environment (please complete the following information):**
https://mjml.io/try-it-live/qWRH2wFJDD

**Email sending environment(for rendering issues)**:
N/A

**Affected email clients (for rendering issues):**
N/A

### PR DESCRIPTION
**Pull request by dazgreer**
**What:** 
Updated `mj-table` to respect the `cellspacing` attribute

**Why:** 
Was not being respected

**How:** 
The issue was that `border-collapse` was set to `collapse`. The update sets to `separate` when `cellspacing` attribute is added to `mj-table` tag

- Added automated test
- Tested across all supported clients in MJ 

fixes #2995

### CODE REVIEW

File: packages/mjml-table/src/index.js [hunk 1]
```diff
@@ -69,6 +71,12 @@ export default class MjTable extends BodyComponent {
     return unit === '%' ? width : parsedWidth
   }
 
+  hasCellspacing() {
+    const cellspacing = this.getAttribute('cellspacing')
+    const numericValue = parseFloat(String(cellspacing).replace(/[^\d.]/g, ''))
+    return numericValue > 0 && typeof cellspacing !== 'undefined'
```
Comment (totocap) [inline packages/mjml-table/src/index.js]: Is `return !isNaN(numericValue) && numericValue > 0` better?
