### PR TITLE
fix(mjml-accordion): font-family / padding-x  #2997

### LINKED ISSUE #2997: mj-accordion bugs (font-family and padding-x)
**Describe the bug**

1. When setting `font-family` on either `mj-accordion` or `mj-accordion-element`, the specified font is not shown in Outlook.
2. When adding `padding-bottom`, `padding-left`, `padding-right`, `padding-top` attributes to `mj-accordion-title` or `mj-accordion-text`, they are overwritten by the default `padding` value

**To Reproduce**

1. https://mjml.io/try-it-live/0Ze6gE-II1
2. https://mjml.io/try-it-live/FHpBsk7KPj

Font family example output:
Image

**Expected behavior**

1. `font-family` should be serif here as declared in the `font-family` attribute on `mj-accordion`
2. The attributes should be respected and override any default padding declarations

**MJML environment (please complete the following information):**
1. https://mjml.io/try-it-live/0Ze6gE-II1
2. https://mjml.io/try-it-live/FHpBsk7KPj

**Email sending environment(for rendering issues)**:
N/A

**Affected email clients (for rendering issues):**
N/A

### PR DESCRIPTION
**Pull request by dazgreer**
**What:** 
1. Updated mj-accordion to respect the font-family attribute for Outlook 
2. Updated mj-accordion-title and mj-accordion-text to respect the padding-x attributes

**Why:** 
Was not being respected

**How:** 

1. The issue that the `font-family` was only being set on the element HTML tag itself and was not being inherited further down by its children. This update does that.
2. The issue was that `padding` attribute was declared after the 4 `padding-x `attribute in the CSS. The update declares the `padding` before so that the `padding-x` values override it

- Added automated test
- Tested across all supported clients in MJ 

fixes #2997

### CODE REVIEW

File: packages/mjml-accordion/src/AccordionText.js [hunk 1]
```diff
@@ -31,20 +31,21 @@ export default class MjAccordionText extends BodyComponent {
...
         'padding-bottom': this.getAttribute('padding-bottom'),
         'padding-left': this.getAttribute('padding-left'),
         'padding-right': this.getAttribute('padding-right'),
         'padding-top': this.getAttribute('padding-top'),
-        padding: this.getAttribute('padding'),
       },
       table: {
         width: '100%',
         'border-bottom': this.getAttribute('border'),
+        test: 'test',
```
Comment (totocap) [inline packages/mjml-accordion/src/AccordionText.js]: Remove this line

Comment (dazgreer) [reply packages/mjml-accordion/src/AccordionText.js]: I've removed this

**Review by totocap — APPROVED** [review]
