### PR TITLE
fix(mjml-wrapper/mjml-section): border-radius not being applied #2961

### LINKED ISSUE #2961: Border Radius not respecting in the mj-wrapper
**Describe the bug**
When i apply border radius in the mj-wrapper it is not showing 

**To Reproduce**
<mjml>
  <mj-body>
    <mj-wrapper border="1px solid red" border-radius="10px">
    <mj-section>
      <mj-column>

        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>

### PR DESCRIPTION
**Pull request by dazgreer**
mj-wrapper and mj-section were not respecting the border-radius declaration.

Fixes the issue and added an automated test. 

fixes #2961

### CODE REVIEW

File: packages/mjml-section/src/index.js [hunk 1]
```diff
@@ -55,6 +55,8 @@ export default class MjSection extends BodyComponent {
 
     const fullWidth = this.isFullWidth()
 
+    const borderCollapse = this.hasBorderRadius()
```
Comment (guigui64) [inline packages/mjml-section/src/index.js:58]: I think that's a better name for the variable:
```suggestion
    const hasBorderRadius = this.hasBorderRadius()
```

**Review by guigui64 — APPROVED** [review]

**Comment by jtsternberg** [comment]
Awesome, thank you for the heads up @dazgreer
