### PR TITLE
fix #1187 html char codes for navbar icon

### LINKED ISSUE #1187: mj-navbar can work on Android
**You can remove this. It seems my "fix" breaks the hamburger menu in IOS.** 
      
I found that while using the Live Editor the HTML generated symbols for the hamburger menu instead of the ASCII codes. See Screenshots. By Manually editing the output I got the hamburger to work on Android 7.

**Reproduction Steps:**

1. Use the Live Editor on the website.

**Expected behavior:**

Hamburger Menu should not work on Android Mail.

**Observed behavior:**

Hamburger menu does work on Android 7 with proper ASCII &#9776 and &#8855.

**Screenshots and GIFs**

encoding
encoding2

**MJML version:**

Live Editor on website

**Email clients the bug is seen on:**

Android Mail, BlueMail on Android 7.

### PR DESCRIPTION
**Pull request by kmcb777**

### CODE REVIEW

File: packages/mjml-navbar/src/Navbar.js [hunk 1]
```diff
@@ -31,8 +31,8 @@ export default class MjNavbar extends BodyComponent {
     'base-url': null,
     hamburger: null,
     'ico-align': 'center',
-    'ico-open': '9776',
-    'ico-close': '8855',
+    'ico-open': '&#9776',
```
Comment (iRyusa) [inline packages/mjml-navbar/src/Navbar.js]: `; ` missing no ?
